# Generated by Django 5.2.4 on 2025-09-01 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File upload', 'verbose_name_plural': 'File uploads'},
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='transcirbed_txt',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='transcribed_txt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(help_text='Allowed: mp3, wav, m4a, flac, ogg, mp4, mov.', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'flac', 'ogg', 'mp4', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
