# Generated by Django 5.2.4 on 2025-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_alter_fileupload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='transcribed_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
